apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogeyJhdXRoIjogIlJtRmpkRzkwZFcwNE9tZG9jRjlWTm5STlZXcFFlVll3VDI0MmRsUlJUMkoyUmpkWGMyOTVWRnBKVkdNd1JVaHFNems9In0KCX0sCgkiY3JlZHNTdG9yZSI6ICJkZXNrdG9wIiwKCSJjdXJyZW50Q29udGV4dCI6ICJkZXNrdG9wLWxpbnV4Igp9==
type: kubernetes.io/dockerconfigjson
