apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-service
  labels:
    app: events-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: events-service
  template:
    metadata:
      labels:
        app: events-service
    spec:
      containers:
        - name: events-service
          image: ghcr.io/Factotum8/architecture-pro-cinemaabyss/events-service:latest
          ports:
            - containerPort: 8000
          env:
            - name: KAFKA_BROKER
              value: "kafka:9092"   # Kafka service name inside the cluster
            - name: KAFKA_TOPIC
              value: "movies"
          readinessProbe:             # ensures pod is ready before traffic
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:              # restarts pod if it crashes
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
